[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
hello_world = "2r5zb8wfdk2b1so7vPzd2HaXXnxrr2gkQjRoNkmDB5r4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/temp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
